# Generated by Django 3.1.7 on 2021-04-05 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0002_auto_20210405_0345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='click',
            old_name='time',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='view',
            old_name='time',
            new_name='datetime',
        ),
    ]
